AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This SAM Application provides the base Lambda Layers to run PHP projects as Lambda Functions

Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-php-74
    Description: This SAM Application provides the base Lambda Layer to run PHP projects as Lambda Functions
    Author: gbmcarlos
    SpdxLicenseId: MIT
    LicenseUrl: ./LICENSE.txt
    ReadmeUrl: ./README.md
    HomePageUrl: https://github.com/gbmcarlos/stacks
    SourceCodeUrl: https://github.com/gbmcarlos/stacks
    SemanticVersion: '0.0.1'

Resources:
  PhpBinLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: php-74
      Description: This layer provides PHP and Composer binaries under /opt/bin/
      CompatibleRuntimes:
        - provided
      ContentUri: ./php-bin.zip
  LatestPhpBinLayerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: latest-php-74-lambda-layer
      Type: String
      Value: !Ref PhpBinLayer
Outputs:
  PhpBinLayerArn:
    Value: !Ref PhpBinLayer
    Description: ARN of the latest PHP bin layer
